// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuk3OzKf1yTRZIvpTl9JeFPTdudJ4zSdM',
    appId: '1:490842727154:android:30de49e3f7a5581413666b',
    messagingSenderId: '490842727154',
    projectId: 'test123-76ede',
    storageBucket: 'test123-76ede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBX3tAW5rzoH-H-G2-KvSL3KOTP3cwIgY',
    appId: '1:490842727154:ios:5a855cc2eb01b8bc13666b',
    messagingSenderId: '490842727154',
    projectId: 'test123-76ede',
    storageBucket: 'test123-76ede.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBAMjtMY9p5nHiP_1r7zKZ20S9osXHP28',
    appId: '1:490842727154:web:9a5e766f432d18f513666b',
    messagingSenderId: '490842727154',
    projectId: 'test123-76ede',
    authDomain: 'test123-76ede.firebaseapp.com',
    storageBucket: 'test123-76ede.firebasestorage.app',
    measurementId: 'G-3BYZNCBT73',
  );
}
